#' Example matrix for use functions
#'
#' @docType data
#'
#' @usage data(PRJNA208535_matrix)
#'
#' @format A 1657x22 matrix with species in columns and samples in rows
#' @keywords data
#'
"PRJNA208535_matrix"

#' Example phyloseq for use functions
#'
#' @docType data
#'
#' @usage data(example_pseq)
#'
#' @format A phyloseq object: otu_table (1657x22),tax_table (22x7) and
#'  sam_data (1657x25)
#' @keywords data
#'
"example_pseq"

#' Example phyloseq for use functions
#'
#' @docType data
#'
#' @usage data(SRA022855)
#'
#' @format A phyloseq object generated by our methodology, corresponding to the ENA data with identifier SRA022855.
#' @keywords data
#'
"SRA022855"

#' Example phyloseq for use functions
#'
#' @docType data
#'
#' @usage data(SRA051298)
#'
#' @format A phyloseq object generated by our methodology, corresponding to the ENA data with identifier SRA051298.
#' @keywords data
#'
"SRA051298"

#' Example phyloseq for use functions
#'
#' @docType data
#'
#' @usage data(PRJNA208535)
#'
#' @format A phyloseq object generated by our methodology, corresponding to the ENA data with identifier PRJNA208535.
#' @keywords data
#'
"PRJNA208535"

#' Example phyloseq for use functions
#'
#' @docType data
#'
#' @usage data(PRJNA797778)
#'
#' @format A phyloseq object generated by our methodology, corresponding to the ENA data with identifier PRJNA797778.
#' @keywords data
#'
"PRJNA797778"

#' Example phyloseq for use functions
#'
#' @docType data
#'
#' @usage data(PRJNA302078)
#'
#' @format A phyloseq object generated by our methodology, corresponding to the ENA data with identifier PRJNA302078.
#' @keywords data
#'
"PRJNA302078"
